//try-catch block format

// try {
//     console.log(c+d)
// }   catch(err) {
//     // do something here...
// }


//throw block
// try {
//     throw new Error();
// } catch(err) {
//     console.log(err)
// }


try {
    console.log(a+b)
} catch(err) {
    console.log(err)
    console.log('There was an error')
    console.log('The error was saved in the error log')
}
console.log("My program does not stop")